### ISSUE TITLE
When ember-cli-typescript is installed, some generators don't work

### ISSUE THREAD

**Issue by nucleartide** [locks/ember-cli-typescript#4]
Here's my Ember version info:

```
 ~/Repositories/typescript-test  $ ember -v
ember-cli: 2.7.0
node: 4.2.2
os: darwin x64
```

Here are two examples of generators that don't work:

```
 ~/Repositories/typescript-test $ ember g route application
installing route
Unknown blueprint: route
```

```
 ~/Repositories/typescript-test $ ember g util add-numbers
installing util
  create addon/utils/add-numbers.ts
  create app/utils/add-numbers.js
installing util-test
Unknown blueprint: util-test
```

**Comment by emin93** [comment]
I have the same problem, but for me i can't generate anything. And for components i get a different error:
`Emins-MacBook-Pro:tstest emin53$ ember install:addon ember-cli-typescript
DEPRECATION: This command has been deprecated. Please use `ember install <addonName>` instead.
Installed packages for tooling via npm.
Installed addon package.
Emins-MacBook-Pro:tstest emin53$ ember generate component test
Cannot find module '../../lib/models/blueprint'
Error: Cannot find module '../../lib/models/blueprint'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/emin53/WebstormProjects/tstest/node_modules/ember-cli-typescript/blueprints/component-addon/index.js:1:81)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)`
